### ISSUE TITLE
Пояснительная записка

### ISSUE THREAD

**Issue by leosavelka** [leosavelka/Kursovaya_LNT#1]
Задачи руководителя

1.	Оформить пояснительную записку.
a.	Введение содержащее видение продукта
b.	Функциональная диаграмма продукта как он видится

Задачи проектировщика

1.	Придумать и обосновать архитектуру продукта
2.	Написать требования к системному ПО (ОС, СУБД) 
3.	Оформить архитектурные диаграммы в составе
a.	Архитектурная диаграмма 
b.	Функциональная диаграмма UML
c.	Диаграмма последовательности UML (для одной выбранной ключевой функции)
d.	При наличии БД концептуальную модель БД
4.	Подготовить часть пояснительной записки. Раздел Проектирование
5.	Отчитываться о ходе выполнения перед руководителем (закрыть задачи)
6.	Результаты работ выложить в репозиторий 

Задачи разработчика

1.	Подобрать языки программирования в соответствии с системным ПО, обосновать выбор.
2.	На основании проекта реализовать продукт, достаточно версии [MVP]
3.	Оформить диаграмму [пакетов] UML для своего продукта
4.	При наличии СУБД оформить диаграмму физической модели
5.	Подготовить материалы для включения в ПЗ
a.	Код – в приложение А
b.	Диаграммы

**Comment by NikitinDmitriy** [comment]
блок проектирования:
 Архитектура продукта

Архитектура продукта "Приложение для шифрования файлов" должна быть разработана с учетом удобства использования. 
В основе архитектуры должны лежать следующие компоненты:

1. Пользовательский интерфейс: обеспечивает пользовательский ввод и вывод, позволяет выбрать файлы для шифрования и отображает результаты операций.
2. Компонент шифрования файлов: обрабатывает выбранные файлы и передает их на компонент алгоритма шифрования.
3. Компонент алгоритма шифрования: выполняет шифрование выбранных файлов на основе алгоритма шифрования AES 128.
4. Хранилище зашифрованных файлов: сохраняет зашифрованные файлы на устройстве, чтобы они могли быть восстановлены или переданы другим получателям.
Обоснование:
1. Безопасность: архитектура продукта должна обеспечивать высокий уровень безопасности данных. Использование современных алгоритмов шифрования.
2. Удобство использования: пользователю должно быть легко и понятно работать с приложением. Интерфейс должен быть интуитивно понятным, а функционал шифрования и дешифрования должен быть доступен в несколько кликов. Кроме того, приложение должно поддерживать работу с файлами различных форматов.
Требования к ПО:
Программа работает на ОС: Windows, Linux, MacOS.

**Comment by 8u66le** [comment]
Блок разработчика.

При сравнении двух языков программирования Java и C# оба языка являются мощными и широко используемыми языками программирования, но есть несколько факторов, которые могут указывать на то, что Java может быть более предпочтительным выбором в данном случае:
Платформонезависимость: Java известен своей платформонезависимостью благодаря виртуальной машине Java (JVM). Это означает, что приложение, написанное на Java, будет работать на разных операционных системах (Windows, macOS, Linux) без необходимости перекомпиляции. Исходя из универсальности Java будет подойдет лучше, чем C#.  Так как, приложение сможет использоваться на разных платформах.
Большое сообщество разработчиков: Java имеет огромное сообщество разработчиков, что означает, что существует множество ресурсов, библиотек, фреймворков и поддержку. 
Богатая экосистема: Java имеет множество библиотек и инструментов, которые могут помочь в разработке и реализации алгоритма шифрования AES-128. Существует множество сторонних библиотек, таких как Bouncy Castle, которые предоставляют реализацию AES-128 и других криптографических алгоритмов, что значительно упрощает разработку приложения.
Безопасность: Java известен своими встроенными механизмами безопасности. У него есть механизмы для проверки подлинности и авторизации, а также API для выполнения криптографических операций. Это эффективно при разработке безопасного приложения шифрования файлов.  
Хотя и C# также может успешно реализовать шифрование файлов с использованием алгоритма AES-128, учитывая вышеперечисленные факторы, Java представляется более подходящим выбором для данного проекта.

**Comment by leosavelka** [comment]
[ПЗ.docx](https://github.com/leosavelka/Kursovaya_LNT/files/13926575/default.docx)
