### ISSUE TITLE
Диаграммы

### ISSUE THREAD

**Issue by leosavelka** [leosavelka/Kursovaya_LNT#2]
Видение проекта:
Целью нашего приложения является предоставление пользователям простого, но эффективного инструмента для шифрования и дешифрования файлов с использованием алгоритма AES-128. Пользователи смогут безопасно хранить и передавать свои конфиденциальные данные с минимальными затратами на время и ресурсы.
Сделать следующие диаграммы:
Савелий:
Функциональная диаграмма продукта как он видится
Дмитрий:
Архитектурная диаграмма
Функциональная диаграмма UML
Диаграмма последовательности UML (для одной выбранной ключевой функции)
Вячеслав:
Диаграмма пакетов UML

**Comment by NikitinDmitriy** [comment]
добавлена функциональная диаграмма

**Comment by leosavelka** [comment]
Дима, добавь в диаграмму возможность работы с только что зашифрованным файлом, а так же возможность сохранения ключа в буфер обмена

**Comment by NikitinDmitriy** [comment]
добавлена диаграмма последовательности для функции шифрования

**Comment by NikitinDmitriy** [comment]
добавленна архитектурная диаграмма

**Comment by 8u66le** [comment]
Выгрузил диаграмму пакетов
