### ISSUE TITLE
Разработка

### ISSUE THREAD

**Issue by leosavelka** [leosavelka/Kursovaya_LNT#3]
Исходя из предоставленных Димой UML-диаграмм необходимо разработать программу, которая шифрует файл. На вход программа принимает файл и ключ. Шифрование должно осуществляться по симметричному алгоритму AES 128. Также тебе необходимо реализовать GUI-интерфейс.

**Comment by 8u66le** [comment]
Проект выгрузил. Проверь на соответствие UML-диаграммам.

**Comment by 8u66le** [comment]
Выгрузил диаграмму пакетов

**Comment by leosavelka** [comment]
Проект создает файл только по одному указанному пути, так как ты указал путь своего рабочего стола. Исправь, а также добавь в приложении возможность пользователю сгенерировать ключ при необходимости.

**Comment by 8u66le** [comment]
Ошибку увидел, принял в работу.

**Comment by 8u66le** [comment]
Проблему исправил, возможность генерации пользователем ключа добавил.
